services:
  # Aplicación Laravel
  app:
    build:
      context: ./melodia-emja  # Apunta a la raíz del proyecto (melodia-emja)
      dockerfile: Dockerfile
    container_name: melodia-emja
    volumes:
      - ./melodia-emja:/var/www/html
    networks:
      - app-network
    expose:
      - "9000"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: 
    depends_on:
      - db

  # Nginx como proxy inverso
  nginx:
    build:
      context: ./nginx  # Esto debe apuntar a la carpeta donde está tu configuración de Nginx (dentro de docker)
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - app
      - phpmyadmin

  # Base de datos MySQL
  db:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "3307:3306"

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "5050:80"
    networks:
      - app-network
    depends_on:
      - db

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
    driver: local
